[tool.poetry]
name = "PyScriptTools"
version = "4.3.12"
description = ""
authors = ["shervinbdndev <shervin2234@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.0"
GPUtil = ""
sockets = ""
colorama = ""
python-cfonts = ""
setuptools = ""
wheel = ""
getmac = ""
psutil = ""

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"